services:
    cluster7-sandbox-apache-php:
        build:
            context: .
            dockerfile: dockerfile
        container_name: mega-uwu
        restart: unless-stopped
        ports:
            - "1307:80"
        environment:
            - APP_DEBUG=true
            - LOG_LEVEL=debug
        networks:
            - laravel-net
        volumes:
        - .:/var/www/html    

networks:
    laravel-net:
        driver: bridge